./: {*/ -build/ -docs/} docs/doc{**} doc{README.md PACKAGE-README.md} legal{LICENSE} manifest

legal{*}:    install = share/doc/box3d/
doc{*}:      install = share/doc/box3d/
docs/doc{*}:
{
  install = share/doc/box3d/docs/
  install.subdirs = true
}

# Don't install tests.
#
tests/: install = false
